import { Platform } from 'react-native';

export const Colors = {
  light: {
    background: '#F8F6F0',
    surface: '#FFFFFF',
    surfaceDim: '#D9DAD7',
    surfaceBright: '#F9FAF6',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#F3F4F0',
    surfaceContainer: '#EDEEEB',
    surfaceContainerHigh: '#E8E8E5',
    surfaceContainerHighest: '#E2E3DF',
    onBackground: '#1A1C1A',
    onSurface: '#1A1C1A',
    onSurfaceVariant: '#414943',
    inverseSurface: '#2F312F',
    inverseOnSurface: '#F0F1ED',
    outline: '#717973',
    outlineVariant: '#C1C8C1',
    surfaceTint: '#3D6751',
    primary: '#3D6751',
    onPrimary: '#FFFFFF',
    primaryContainer: '#A8D5BA',
    onPrimaryContainer: '#345D48',
    inversePrimary: '#A4D1B6',
    secondary: '#48626F',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#C8E4F3',
    onSecondaryContainer: '#4C6673',
    tertiary: '#835053',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FCBABD',
    onTertiaryContainer: '#79474B',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#93000A',
    primaryFixed: '#BFEDD1',
    primaryFixedDim: '#A4D1B6',
    onPrimaryFixed: '#002113',
    onPrimaryFixedVariant: '#254F3A',
    secondaryFixed: '#CBE7F6',
    secondaryFixedDim: '#AFCBDA',
    onSecondaryFixed: '#011F2A',
    onSecondaryFixedVariant: '#304A57',
    tertiaryFixed: '#FFDADB',
    tertiaryFixedDim: '#F7B6B9',
    onTertiaryFixed: '#340F13',
    onTertiaryFixedVariant: '#68393D',
    surfaceVariant: '#E2E3DF',
    text: '#1A1C1A',
    textSecondary: '#414943',
    textTertiary: '#717973',
    tint: '#3D6751',
    icon: '#717973',
    tabIconDefault: '#717973',
    tabIconSelected: '#3D6751',
    success: '#3D6751',
    warning: '#F7DC8E',
    danger: '#E8A0A0',
  },
  dark: {
    background: '#1A1C1A',
    surface: '#2F312F',
    surfaceDim: '#1A1C1A',
    surfaceBright: '#2F312F',
    surfaceContainerLowest: '#141614',
    surfaceContainerLow: '#1A1C1A',
    surfaceContainer: '#222422',
    surfaceContainerHigh: '#2C2E2C',
    surfaceContainerHighest: '#373937',
    onBackground: '#E2E3DF',
    onSurface: '#E2E3DF',
    onSurfaceVariant: '#C1C8C1',
    inverseSurface: '#E2E3DF',
    inverseOnSurface: '#2F312F',
    outline: '#8B938C',
    outlineVariant: '#414943',
    surfaceTint: '#A4D1B6',
    primary: '#A4D1B6',
    onPrimary: '#1A3B2A',
    primaryContainer: '#254F3A',
    onPrimaryContainer: '#BFEDD1',
    inversePrimary: '#3D6751',
    secondary: '#AFCBDA',
    onSecondary: '#1A3440',
    secondaryContainer: '#304A57',
    onSecondaryContainer: '#CBE7F6',
    tertiary: '#F7B6B9',
    onTertiary: '#4E2428',
    tertiaryContainer: '#68393D',
    onTertiaryContainer: '#FFDADB',
    error: '#FFB4AB',
    onError: '#690005',
    errorContainer: '#93000A',
    onErrorContainer: '#FFDAD6',
    primaryFixed: '#BFEDD1',
    primaryFixedDim: '#A4D1B6',
    onPrimaryFixed: '#002113',
    onPrimaryFixedVariant: '#254F3A',
    secondaryFixed: '#CBE7F6',
    secondaryFixedDim: '#AFCBDA',
    onSecondaryFixed: '#011F2A',
    onSecondaryFixedVariant: '#304A57',
    tertiaryFixed: '#FFDADB',
    tertiaryFixedDim: '#F7B6B9',
    onTertiaryFixed: '#340F13',
    onTertiaryFixedVariant: '#68393D',
    surfaceVariant: '#414943',
    text: '#E2E3DF',
    textSecondary: '#C1C8C1',
    textTertiary: '#8B938C',
    tint: '#A4D1B6',
    icon: '#8B938C',
    tabIconDefault: '#8B938C',
    tabIconSelected: '#A4D1B6',
    success: '#A4D1B6',
    warning: '#F7DC8E',
    danger: '#E8A0A0',
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: 'Plus Jakarta Sans',
    serif: 'ui-serif',
    rounded: 'Plus Jakarta Sans',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'Plus Jakarta Sans',
    serif: 'serif',
    rounded: 'Plus Jakarta Sans',
    mono: 'monospace',
  },
  web: {
    sans: "'Plus Jakarta Sans', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'Plus Jakarta Sans', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});

export const Typography = {
  display: { fontSize: 40, fontWeight: '600' as const, lineHeight: 48, letterSpacing: -0.02 },
  h1: { fontSize: 32, fontWeight: '600' as const, lineHeight: 40, letterSpacing: -0.01 },
  h2: { fontSize: 24, fontWeight: '500' as const, lineHeight: 32, letterSpacing: -0.01 },
  h3: { fontSize: 20, fontWeight: '500' as const, lineHeight: 28, letterSpacing: 0 },
  bodyLg: { fontSize: 18, fontWeight: '400' as const, lineHeight: 28, letterSpacing: 0 },
  bodyMd: { fontSize: 16, fontWeight: '400' as const, lineHeight: 24, letterSpacing: 0 },
  bodySm: { fontSize: 14, fontWeight: '400' as const, lineHeight: 20, letterSpacing: 0 },
  labelMd: { fontSize: 12, fontWeight: '600' as const, lineHeight: 16, letterSpacing: 0.04 },
  labelSm: { fontSize: 10, fontWeight: '600' as const, lineHeight: 12, letterSpacing: 0.05 },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  gutter: 24,
  margin: 32,
};

export const Radius = {
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  full: 9999,
};
